// micro-react/src/pages/counter.jsx
import React, { useState } from 'react';
import { triggerEvent } from '../utils/events';

const initialCount = 0;
const buttonStep = 1;

export default function Counter() {
  const [ count, setCount ] = useState(initialCount);

  function handleCountChange(step, count) {    
    triggerEvent('countChange', { step, count })
  }

  function increaseCountBy(step) {
    return () => {
      setCount((prev) => {
        const result = prev + step;

        handleCountChange(step, result)

        return prev + step;
      });
      
    };
  }

  return (
    <div className="counter">
      <h1>React Counter</h1>
      <div>
        <span>{ `Count: ${ count }` }</span>
        <button onClick={ increaseCountBy(-buttonStep) }>
          -
        </button>
        <button onClick={ increaseCountBy(buttonStep) }>
          +
        </button>
      </div>
    </div>
  );
}

// micro-vue/src/Counter.vue
<template>
  <div class="counter">
    <h1>Vue Counter</h1>
    <span>Count: {{ count }}</span>
    <button @click="decrement">-</button>
    <button @click="increment">+</button>
  </div>
</template>

<script>
import { triggerEvent } from "./utils/events.js"

export default {
  name: "Counter",
  data() {
    return { triggerEvent, count: 0 };
  },
  methods: {
    increment() {
      this.count++;
      triggerEvent('countChange', { step: 1, count: this.count });
    },
    decrement() {
      this.count--;
      triggerEvent('countChange', { step: -1, count: this.count });
    },
  },
};
</script>
